apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hellowhale-deployment
  labels:
    name: webapplication
    app: demo
spec:
  replicas: 3
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: webapplication
        app: demo
    spec:
      containers:
      - name: hellowhale
        image: manojnaladala/devops:38
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred 
